### ISSUE TITLE
Does not work on spotify and nightbot.tv

### ISSUE THREAD

**Issue by gh291** [rain-fighters/AudioPick#15] opened 2018-04-07 05:07 UTC
I stream on twitch and would love to have my viewers get some music, but spotify and https://beta.nightbot.tv/song_requests is not working on audio routing. Right now I am able to get by using "Audio Router" but I would much prefer a chrome extension, I hate running to many executable taking up valuable resources that would be better used on my games or OBS.

System info:
Win 10 pro x64
chrome version 65
32gb ram
I7 7700k
EVGA superclocked nvidia Gtx 980
other chrome extensions:NONE

**Comment by necropola** [comment] 2018-04-08 13:32
Duplicate of issue #2

**Closed by necropola** 2018-04-08 13:32 UTC
