### ISSUE TITLE
after reinstall, audio pick refuses to work

### ISSUE THREAD

**Issue by Liquidmasl** [rain-fighters/AudioPick#37] opened 2020-04-22 17:12 UTC
Not sure how I should debug that issue. 

AudioPick worked fine for me until I reinstalled windows and therefor chrome. 

After that it refuses to work. 
When clicking on the extension icon it shows all audio devices, but when i go into extension options i am presented with an empty list (there is one unnamed object with tickmark). I am pretty sure this list was not empty before i did the reinstall so it might have something todo with that?

![image](https://user-images.githubusercontent.com/10048306/80012062-08431e80-84cd-11ea-9033-1020c5136042.png)

![image](https://user-images.githubusercontent.com/10048306/80012086-12651d00-84cd-11ea-94eb-c9685e36a2ca.png)

If there is any more information i can provide i would be happy to.
This extension is a godsend and i miss its functionality dearly!

**Comment by mkersting** [comment] 2020-04-22 20:54
Sub. I have the same Problem. 
BUT After a Windows reboot, the choosen Device changed. But i do not always have to reboot Windows. It should work "on the fly". 
I think it might do but in without "instant change" this is useless for me.

If you need more Information about my Audio configuration, please write me :-) 
When I can send you a "Bug report" please tell me how to do so... 

And Anyway: Thanks for the work

**Comment by necropola** [comment] 2020-04-23 18:32
duplicate of #36

**Closed by necropola** 2020-04-23 18:32 UTC
Labels: bug, duplicate
