### ISSUE TITLE
Crunchyroll

### ISSUE THREAD

**Issue by Kdenight** [rain-fighters/AudioPick#54] opened 2024-02-07 01:37 UTC
enabled mic 
tried refreshing many times
tried default to device output i wanted still nothing
tried this other extension out called AuRo did not work too
works on other sites like youtube and hidive
just will not work on crunchyroll.
not sure what else to say

**Comment by necropola** [comment] 2024-02-07 10:03
This site uses (for whatever reason) an iframe to display the videos:
```html
<iframe class="video-player" allow="autoplay; fullscreen; encrypted-media *" allowfullscreen="" src="https://static.crunchyroll.com/vilos-v2/web/vilos/player.html" title="Video Player">
    <p>Your browser does not support iframes.</p>
</iframe>
```

The issue is that unless this iframe explicitely allows microphone access, we will not be able to switch audio devices within. This is a restriction that has been added to  chrome (and firefox, and ...) a while ago. and is the reason why AudioPick-0.3.10 does not inject itself into sub-frames anymore.

If the iframe looked like (spot the difference`?)
```html
<iframe class="video-player" allow="autoplay; fullscreen; encrypted-media *; microphone" allowfullscreen="" src="https://static.crunchyroll.com/vilos-v2/web/vilos/player.html" title="Video Player">
    <p>Your browser does not support iframes.</p>
</iframe>
```

and we would add  `"all_frames" : true` to `manffest.json` it would probably work. So unless you control the site's source code you are currently out of luck. See #52.

**Comment by necropola** [comment] 2024-11-06 12:01
Closing due to lack of resources. "Iframe" or rather "all_frames" support will probably not happen anytime soon.

**Closed by necropola** 2024-11-06 12:01 UTC
